apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1710627727644
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000